# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

"""Credential interface placeholder; authentication is implemented separately."""

from pydantic import BaseModel, Field


class TokenModel(BaseModel):
    """Verified caller identity; no bearer credential is retained."""

    username: str
    uid: str | None = None
    groups: list[str] = Field(default_factory=list)
