# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

"""Fail-closed authentication extension point for the generated scaffold."""

from fastapi import Request

from training_service.auth import authenticate_request
from training_service_api.models.extra_models import TokenModel


async def get_token_OpenShiftBearer(request: Request) -> TokenModel:
    """Validate the caller and return only verified identity fields."""
    token = await authenticate_request(request)
    return token
